### PR TITLE
Clean `compute_stats_zurich` script - move functions under `utils` folder

### PR DESCRIPTION
**Pull request by valosekj**
This PR cleans the main `compute_stats_zurich` script by introducing the `utils` folder:

```
└── utils
    ├── generate_figures.py             # functions for plotting
    ├── read_files.py                   # functions for reading input files
    └── utils.py                        # various utility functions
```

The PR also makes the script compatible with XLSX files under the `phenotype` folder (context [here](https://github.com/neuropoly/data-management/issues/256)).

### CODE REVIEW

**Comment by sandrinebedard** [comment]
~~~
 python statistics/compute_stats_zurich.py -input-file /mnt/r/dcm-zurich_2023-08-13_persex/results/compression_metrics.csv -participants-file /mnt/y/sebeda/participants.tsv -clinical-file /mnt/c/Users/sb199/Projet3_data/DCM_norm_PAM50/phenotype/clinical_scores.xlsx -electro-file /mnt/c/Users/sb199/Projet3_data/DCM_norm_PAM50/phenotype/electrophysiological_measurements.xlsx -path-out /mnt/c/Users/sb199/Projet3_data/DCM_norm_PAM50/test_2023-09-04
~~~


Got this error:

~~~
Excluded subjects: []
Reading: /mnt/c/Users/sb199/Projet3_data/DCM_norm_PAM50/phenotype/clinical_scores.xlsx
/mnt/c/Users/sb199/dcm_metric_normalization/statistics/utils/read_files.py:154: FutureWarning: The default value of regex will change from True to False in a future version.
  clinical_df.columns = clinical_df.columns.str.replace('.1', '_6m')
/mnt/c/Users/sb199/dcm_metric_normalization/statistics/utils/read_files.py:155: FutureWarning: The default value of regex will change from True to False in a future version.
  clinical_df.columns = clinical_df.columns.str.replace('.2', '_12m')
Dropping columns with more than 25% nan values:
 Index(['total_mjoa_6m', 'total_mjoa_12m', 'lt_cervical_tot_6m',
       'lt_cervical_tot_12m', 'pp_cervical_tot_6m', 'pp_cervical_tot_12m',
       'total_dorsal_6m', 'total_dorsal_12m'],
      dtype='object')
Correlation matrix saved to: /mnt/c/Users/sb199/Projet3_data/DCM_norm_PAM50/test_2023-09-04/corr_matrix_clinical_scores.png
Generating pairplot...(it may take a while)...
Pairplot saved to: /mnt/c/Users/sb199/Projet3_data/DCM_norm_PAM50/test_2023-09-04/pairplot_clinical_scores.png
Reading: /mnt/c/Users/sb199/Projet3_data/DCM_norm_PAM50/phenotype/electrophysiological_measurements.xlsx
Traceback (most recent call last):
  File "statistics/compute_stats_zurich.py", line 808, in <module>
    main()
  File "statistics/compute_stats_zurich.py", line 704, in main
    args.electro_file, df_participants)
  File "/mnt/c/Users/sb199/dcm_metric_normalization/statistics/utils/read_files.py", line 180, in read_electrophysiology_anatomical_and_motion_file
    'aMSCC_C3toC2', 'aMSCC_C4toC2', 'aMSCC_C5toC2', 'aMSCC_C6toC2', 'aMSCC_C7toC2']]
  File "/home/sabeda/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/sabeda/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/sabeda/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['aSCOR_C2', 'aSCOR_C3', 'aSCOR_C4', 'aSCOR_C5', 'aSCOR_C6', 'aSCOR_C7', 'aSCOR_C2_6mth', 'aSCOR_C3_6mth', 'aSCOR_C4_6mth', 'aSCOR_C5_6mth', 'aSCOR_C6_6mth', 'aSCOR_C7_6mth', 'aSCOR_C2_12mth', 'aSCOR_C3_12mth', 'aSCOR_C4_12mth', 'aSCOR_C5_12mth', 'aSCOR_C6_12mth', 'aSCOR_C7_12mth', 'aMSCC_C3toC2', 'aMSCC_C4toC2', 'aMSCC_C5toC2', 'aMSCC_C6toC2', 'aMSCC_C7toC2'] not in index"
~~~


Am I specifying the right file? now that the data is seperated in the new git annexed phenotype files, don't we have more arguments to input?

**Comment by valosekj** [comment]
> Am I specifying the right file? now that the data is seperated in the new git annexed phenotype files, don't we have more arguments to input?

You are right! I tested the PR with the "old" files. --> the arg parser has to be updated to be compatible with the git-annex phenotype folder.

**Comment by valosekj** [comment]
@sandrinebedard I made the scripts compatible with XLSX files located under the `phenotype` folder in https://github.com/sct-pipeline/dcm-metric-normalization/pull/21/commits/44fcf7986e02612b42f116faa2fe3bae59ee39e2.

You can try the script with the following command:

```
python statistics/compute_stats_zurich.py
-input-file
results/compression_metrics.csv
-participants-file
dcm-zurich/participants.tsv
-clinical-file
dcm-zurich/phenotype/clinical_scores.xlsx
-anatomical-file
dcm-zurich/phenotype/anatomical_data.xlsx
-electro-file
dcm-zurich/phenotype/electrophysiological_measurements.xlsx
-motion-file
dcm-zurich/phenotype/motion_data.xlsx
-path-out
statistics
```

**Review by sandrinebedard — APPROVED** [review]
I was able to run everything!

**Pull request merged**
